#! /bin/sh
#

# Source function library.
. /etc/init.d/functions

# Check that networking is up.
. /etc/sysconfig/network

if [ "$NETWORKING" = "no" ]
then
	exit 0
fi

RETVAL=0
prog="sword"
binfile=/home/elrond/cms/vendor/bin/sword
phpbin=/usr/local/php56/bin/php
runuser=elrond
appkey=032aef3271ec75e661805d0edf791b93

start () {
	echo -n $"Starting $prog... "
	daemon --user ${runuser} "$phpbin $binfile ${appkey} --daemonize yes" &
}
stop () {
	echo -n $"Stopping $prog... "
	NAME=${appkey}
	ID=`ps -ef | grep "$NAME" | grep -v "grep" | awk '{print $2}'`
	for id in $ID
	do
		kill -9 $id
	done
}

restart () {
        stop
        start
}


# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	status -p ${pidfile} sword
	RETVAL=$?
	;;
  restart)
	restart
	;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 2
esac

exit $RETVAL
